// <auto-generated />
using System;
using BananaPay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BananaPay.Migrations
{
    [DbContext(typeof(BananaPayContext))]
    [Migration("20251114152800_addCliente")]
    partial class addCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BananaPay.Models.Conta", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfDono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContaId");

                    b.HasIndex("CpfDono")
                        .IsUnique();

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("BananaPay.Models.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("TransacaoId");

                    b.HasIndex("ContaId");

                    b.HasIndex("ContaId1");

                    b.ToTable("Transacoes");

                    b.HasDiscriminator<string>("Tipo").HasValue("Transacao");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BananaPay.Models.Deposito", b =>
                {
                    b.HasBaseType("BananaPay.Models.Transacao");

                    b.HasDiscriminator().HasValue("Deposito");
                });

            modelBuilder.Entity("BananaPay.Models.Saque", b =>
                {
                    b.HasBaseType("BananaPay.Models.Transacao");

                    b.HasDiscriminator().HasValue("Saque");
                });

            modelBuilder.Entity("BananaPay.Models.Transferencia", b =>
                {
                    b.HasBaseType("BananaPay.Models.Transacao");

                    b.Property<int>("ContaDestinoId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ContaDestinoId");

                    b.HasDiscriminator().HasValue("Transferencia");
                });

            modelBuilder.Entity("BananaPay.Models.Transacao", b =>
                {
                    b.HasOne("BananaPay.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaPay.Models.Conta", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId1");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("BananaPay.Models.Transferencia", b =>
                {
                    b.HasOne("BananaPay.Models.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaDestino");
                });

            modelBuilder.Entity("BananaPay.Models.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
